
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.showSql=true
hibernate.connection.driverClass=com.mysql.cj.jdbc.Driver

# Thong tin ket noi Aiven MySQL
hibernate.connection.url=jdbc:mysql://my-database-xe-khach-carmanagement.h.aivencloud.com:20489/defaultdb?useSSL=true&requireSSL=true
hibernate.connection.username=avnadmin
# Mật khẩu Aiven của bạn
hibernate.connection.password=${DB_PASSWORD}
