
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

paypal.client.id=ATIqBPrG29ClBGi81HjlLae_BoT02Z5O63QyQSJhCa0OUDfv_UdEeCmnT_je-iayM9DNJqCP9yAREExH
paypal.client.secret=${PAYPAL_CLIENT_SECRET}
paypal.mode=sandbox

